/*
 * This source file was generated by the Gradle 'init' task
 */
package org.lib;
import org.lib.document.Document;
import org.lib.searchengine.SearchEngine;
import java.io.FileNotFoundException; 

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }

    public static void main( String[] args )
    {
        System.out.println( "Hello World!" );
        SearchEngine engine;
        try {
            String[] files = {
                    "/home/simon/simple-search/doc1.txt",
                    "/home/simon/simple-search/doc2.txt",
                    "/home/simon/simple-search/doc3.txt",
                    "/home/simon/simple-search/doc4.txt",
                    "/home/simon/simple-search/doc5.txt",
                    "/home/simon/simple-search/doc6.txt",
                    "/home/simon/simple-search/doc7.txt",
                    "/home/simon/simple-search/doc8.txt",
                    "/home/simon/simple-search/doc9.txt",
                    "/home/simon/simple-search/doc10.txt",
            };
            engine = new SearchEngine(files);
        } catch (FileNotFoundException e) {
            System.out.println("File not found");
            return;
        }
        System.out.println("Contents: "+engine.searchWord("brown"));
        System.out.println("Words: " + engine.mapping.size());
    }


}
