/*
 * This source file was generated by the Gradle 'init' task
 */
package org.lib;

import java.io.FileNotFoundException;
import java.util.Scanner;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }

    public static void main( String[] args )
    {
        System.out.println( "Parsing documents..." );
        long start = System.currentTimeMillis();
        SearchEngine engine;
        try {
            String[] files = {
                    "/home/simon/simple-search/doc1.txt",
                    "/home/simon/simple-search/doc2.txt",
                    "/home/simon/simple-search/doc3.txt",
                    "/home/simon/simple-search/doc4.txt",
                    "/home/simon/simple-search/doc5.txt",
                    "/home/simon/simple-search/doc6.txt",
                    "/home/simon/simple-search/doc7.txt",
                    "/home/simon/simple-search/doc8.txt",
                    "/home/simon/simple-search/doc9.txt",
                    "/home/simon/simple-search/doc10.txt",
            };
            engine = new SearchEngine(files);
        } catch (FileNotFoundException e) {
            System.out.println("File not found");
            return;
        }
        long end = System.currentTimeMillis();
        System.out.printf("Parsing took %s ms\n", end-start);
        System.out.println( "Type the word you would like to search for:" );
        Scanner shell = new Scanner(System.in);
        while(true) {
            String query = shell.nextLine();
            System.out.println("Result: " + engine.searchWord(query));
        }

    }


}
